#!/usr/bin/env bash

# Completion command (generate shell completions)
cmd_completion() {
  if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    show_command_help
  fi

  local shell="${1:-}"

  case "$shell" in
    bash)
      cat "$GTR_DIR/completions/gtr.bash"
      ;;
    zsh)
      # Output zstyle registration + completion loading
      # The zstyle MUST run before compinit to register gtr as a git subcommand
      cat <<EOF
# git-gtr zsh completion
# Generated by: git gtr completion zsh
# Add to ~/.zshrc (before compinit):
#   eval "\$(git gtr completion zsh)"

# Register gtr as a git subcommand (MUST be before compinit)
zstyle ':completion:*:*:git:*' user-commands gtr:'Git worktree management'

# Add completions to fpath and initialize
fpath=($GTR_DIR/completions \$fpath)

# Note: If you already have compinit in your .zshrc, you may want to
# source this file before your existing compinit call and remove the
# autoload line below.
autoload -Uz compinit && compinit -C
EOF
      ;;
    fish)
      cat "$GTR_DIR/completions/git-gtr.fish"
      ;;
    ""|--help|-h)
      echo "Generate shell completions for git gtr"
      echo ""
      echo "Usage: git gtr completion <shell>"
      echo ""
      echo "Shells:"
      echo "  bash    Generate Bash completions"
      echo "  zsh     Generate Zsh completions"
      echo "  fish    Generate Fish completions"
      echo ""
      echo "Examples:"
      echo "  # Bash: add to ~/.bashrc"
      echo "  source <(git gtr completion bash)"
      echo ""
      echo "  # Zsh: add to ~/.zshrc (BEFORE any existing compinit call)"
      echo "  eval \"\$(git gtr completion zsh)\""
      echo ""
      echo "  # Fish: save to completions directory"
      echo "  git gtr completion fish > ~/.config/fish/completions/git-gtr.fish"
      return 0
      ;;
    *)
      log_error "Unknown shell: $shell"
      log_error "Supported shells: bash, zsh, fish"
      log_info "Run 'git gtr completion --help' for usage"
      return 1
      ;;
  esac
}